import React, { useState, useEffect } from 'react';
import { useFirebaseDatabase } from '../hooks/useFirebaseDatabase';
import { FirebaseDatabaseService } from '../services/firebaseDatabase';
import { useFirebaseAuth } from '../hooks/useFirebaseAuth';
import { 
  FileText, 
  Download, 
  BarChart3, 
  Users, 
  Package, 
  Building, 
  TrendingUp, 
  Calendar,
  Filter,
  Search,
  Eye,
  Printer,
  FileSpreadsheet,
  RefreshCw,
  AlertTriangle,
  CheckCircle,
  Clock
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF with autoTable method
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface ReportData {
  inventory: any[];
  users: any[];
  facilities: any[];
  transactions: any[];
  transfers: any[];
}

interface ReportConfig {
  type: 'inventory' | 'users' | 'facilities' | 'transactions' | 'transfers' | 'all';
  format: 'pdf' | 'csv';
  dateRange: 'all' | 'today' | 'week' | 'month' | 'year';
  filters: {
    status?: string;
    category?: string;
    facility?: string;
    role?: string;
  };
}

export default function Reports() {
  const { user } = useFirebaseAuth();
  const { 
    inventoryItems, 
    stockTransactions, 
    facilities, 
    transfers, 
    loading, 
    error 
  } = useFirebaseDatabase();
  const [reportData, setReportData] = useState<ReportData>({
    inventory: [],
    users: [],
    facilities: [],
    transactions: [],
    transfers: []
  });
  const [reportConfig, setReportConfig] = useState<ReportConfig>({
    type: 'inventory',
    format: 'pdf',
    dateRange: 'all',
    filters: {}
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState<string>('');

  // Load all data for reports using the same source as Inventory page
  useEffect(() => {
    const loadReportData = async () => {
      try {
        console.log('Loading report data from Firebase...');
        
        // Get users data separately since it's not in useFirebaseDatabase
        const users = await FirebaseDatabaseService.getUsers();
        
        console.log('Loaded data from Firebase:', {
          inventory: inventoryItems?.length || 0,
          users: users?.length || 0,
          facilities: facilities?.length || 0,
          transactions: stockTransactions?.length || 0,
          transfers: transfers?.length || 0
        });

        setReportData({
          inventory: inventoryItems || [],
          users: users || [],
          facilities: facilities || [],
          transactions: stockTransactions || [],
          transfers: transfers || []
        });
        
        console.log('Report data set successfully');
      } catch (error) {
        console.error('Error loading report data:', error);
      }
    };

    if (inventoryItems && facilities && stockTransactions && transfers) {
      loadReportData();
    }
  }, [inventoryItems, facilities, stockTransactions, transfers]);

  // Generate PDF Report
  const generatePDFReport = async () => {
    setIsGenerating(true);
    try {
      console.log('Starting PDF generation...');
      console.log('Report config:', reportConfig);
      console.log('Report data:', reportData);

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const pageHeight = doc.internal.pageSize.height;
      let yPosition = 20;

      // Header with proper spacing
      doc.setFontSize(18);
      doc.setTextColor(0, 0, 0);
      doc.text('DIMS Inventory Management System', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;

      doc.setFontSize(14);
      doc.text(`Report: ${getReportTitle()}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;

      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 10;

      doc.text(`Generated by: ${user?.displayName || user?.email}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 25; // More space before content

      console.log('Generating report type:', reportConfig.type);

      // Report content based on type
      switch (reportConfig.type) {
        case 'inventory':
          console.log('Generating inventory PDF...');
          generateInventoryPDF(doc, yPosition);
          break;
        case 'users':
          console.log('Generating users PDF...');
          generateUsersPDF(doc, yPosition);
          break;
        case 'facilities':
          console.log('Generating facilities PDF...');
          generateFacilitiesPDF(doc, yPosition);
          break;
        case 'transactions':
          console.log('Generating transactions PDF...');
          generateTransactionsPDF(doc, yPosition);
          break;
        case 'transfers':
          console.log('Generating transfers PDF...');
          generateTransfersPDF(doc, yPosition);
          break;
        case 'all':
          console.log('Generating all reports PDF...');
          generateAllReportsPDF(doc, yPosition);
          break;
        default:
          console.log('Unknown report type:', reportConfig.type);
          doc.setFontSize(14);
          doc.text('Unknown report type', 14, yPosition);
      }

      // Save PDF
      const fileName = `DIMS_${reportConfig.type}_${new Date().toISOString().split('T')[0]}.pdf`;
      console.log('Saving PDF as:', fileName);
      doc.save(fileName);
      
      addNotification('PDF report generated successfully!', 'success');
    } catch (error) {
      console.error('Error generating PDF:', error);
      addNotification('Failed to generate PDF report', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  // Test PDF generation
  const testPDFGeneration = () => {
    try {
      console.log('Testing PDF generation...');
      const doc = new jsPDF();
      
      // Simple test content
      doc.setFontSize(16);
      doc.text('DIMS Test Report', 20, 20);
      doc.setFontSize(12);
      doc.text('This is a test PDF generation', 20, 40);
      doc.text(`Generated at: ${new Date().toLocaleString()}`, 20, 60);
      doc.text(`Report type: ${reportConfig.type}`, 20, 80);
      doc.text(`Data count: ${reportData.inventory?.length || 0} items`, 20, 100);
      
      // Save test PDF
      doc.save('DIMS_Test_Report.pdf');
      // addNotification('Test PDF generated successfully!', 'success'); // This line was removed as per the edit hint
    } catch (error) {
      console.error('Test PDF generation error:', error);
      // addNotification('Test PDF generation failed', 'error'); // This line was removed as per the edit hint
    }
  };

  // Generate CSV Report
  const generateCSVReport = async () => {
    setIsGenerating(true);
    try {
      let csvContent = '';
      let fileName = '';

      switch (reportConfig.type) {
        case 'inventory':
          csvContent = generateInventoryCSV();
          fileName = `DIMS_Inventory_${new Date().toISOString().split('T')[0]}.csv`;
          break;
        case 'users':
          csvContent = generateUsersCSV();
          fileName = `DIMS_Users_${new Date().toISOString().split('T')[0]}.csv`;
          break;
        case 'facilities':
          csvContent = generateFacilitiesCSV();
          fileName = `DIMS_Facilities_${new Date().toISOString().split('T')[0]}.csv`;
          break;
        case 'transactions':
          csvContent = generateTransactionsCSV();
          fileName = `DIMS_Transactions_${new Date().toISOString().split('T')[0]}.csv`;
          break;
        case 'transfers':
          csvContent = generateTransfersCSV();
          fileName = `DIMS_Transfers_${new Date().toISOString().split('T')[0]}.csv`;
          break;
        case 'all':
          csvContent = generateAllReportsCSV();
          fileName = `DIMS_All_Reports_${new Date().toISOString().split('T')[0]}.csv`;
          break;
      }

      // Download CSV
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', fileName);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error generating CSV:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  // Simple PDF generation without autoTable
  const generateSimplePDF = (doc: jsPDF, title: string, data: any[], columns: string[]) => {
    try {
      let yPosition = 20;
      const pageWidth = doc.internal.pageSize.width;
      const margin = 14;
      const columnWidth = (pageWidth - 2 * margin) / columns.length;
      
      // Title
      doc.setFontSize(16);
      doc.text(title, margin, yPosition);
      yPosition += 15;

      // Headers with proper spacing
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      columns.forEach((column, index) => {
        const xPosition = margin + (index * columnWidth);
        doc.text(column, xPosition, yPosition);
      });
      yPosition += 10;

      // Separator line
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Data rows
      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      data.forEach((row, rowIndex) => {
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }
        
        columns.forEach((column, colIndex) => {
          const xPosition = margin + (colIndex * columnWidth);
          const value = row[column] || row[colIndex] || 'N/A';
          const text = String(value).substring(0, Math.floor(columnWidth / 6)); // Limit text length
          doc.text(text, xPosition, yPosition);
        });
        yPosition += 8;
      });
    } catch (error) {
      console.error('Error in simple PDF generation:', error);
      doc.setFontSize(14);
      doc.text('Error generating data', 14, 20);
    }
  };

  const generateInventoryPDF = (doc: jsPDF, startY: number) => {
    try {
      const inventoryData = reportData.inventory || [];
      
      if (inventoryData.length === 0) {
        doc.setFontSize(14);
        doc.text('No inventory data available', 14, startY);
        return;
      }

      // Try autoTable first, fallback to simple PDF
      try {
        const head = [['Name', 'SKU', 'Category', 'Stock', 'Min Stock', 'Cost', 'Supplier', 'Facility', 'Status']];
        const body = inventoryData.map(item => [
          item.name || 'N/A',
          item.sku || 'N/A',
          item.category || 'N/A',
          item.currentStock?.toString() || '0',
          item.minStock?.toString() || '0',
          `UGX ${(item.cost || 0).toLocaleString()}`,
          item.supplier || 'N/A',
          item.facility || 'N/A',
          item.status || 'N/A'
        ]);

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: head,
            body: body,
            startY: startY,
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [255, 204, 0], textColor: [0, 0, 0] },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            margin: { top: 10, right: 10, bottom: 10, left: 10 }
          });
        } else {
          // Fallback to simple PDF with better structure
          const columns = ['Name', 'SKU', 'Category', 'Stock', 'Min Stock', 'Cost', 'Supplier', 'Facility', 'Status'];
          const data = inventoryData.map(item => ({
            Name: item.name || 'N/A',
            SKU: item.sku || 'N/A',
            Category: item.category || 'N/A',
            Stock: item.currentStock?.toString() || '0',
            'Min Stock': item.minStock?.toString() || '0',
            Cost: `UGX ${(item.cost || 0).toLocaleString()}`,
            Supplier: item.supplier || 'N/A',
            Facility: item.facility || 'N/A',
            Status: item.status || 'N/A'
          }));
          generateSimplePDF(doc, 'Inventory Report', data, columns);
        }
      } catch (autoTableError) {
        console.error('AutoTable failed, using simple PDF:', autoTableError);
        // Fallback to simple PDF with better structure
        const columns = ['Name', 'SKU', 'Category', 'Stock', 'Min Stock', 'Cost', 'Supplier', 'Facility', 'Status'];
        const data = inventoryData.map(item => ({
          Name: item.name || 'N/A',
          SKU: item.sku || 'N/A',
          Category: item.category || 'N/A',
          Stock: item.currentStock?.toString() || '0',
          'Min Stock': item.minStock?.toString() || '0',
          Cost: `UGX ${(item.cost || 0).toLocaleString()}`,
          Supplier: item.supplier || 'N/A',
          Facility: item.facility || 'N/A',
          Status: item.status || 'N/A'
        }));
        generateSimplePDF(doc, 'Inventory Report', data, columns);
      }
    } catch (error) {
      console.error('Error generating inventory PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating inventory data', 14, startY);
    }
  };

  const generateUsersPDF = (doc: jsPDF, startY: number) => {
    try {
      const usersData = reportData.users || [];
      
      if (usersData.length === 0) {
        doc.setFontSize(14);
        doc.text('No users data available', 14, startY);
        return;
      }

      // Try autoTable first, fallback to simple PDF
      try {
        const head = [['Name', 'Email', 'Role', 'Phone', 'Facility', 'Status']];
        const body = usersData.map(user => [
          user.name || 'N/A',
          user.email || 'N/A',
          user.role || 'N/A',
          user.phone || 'N/A',
          user.facilityName || 'N/A',
          user.status || 'N/A'
        ]);

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: head,
            body: body,
            startY: startY,
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [255, 204, 0], textColor: [0, 0, 0] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback to simple PDF
          const columns = ['Name', 'Email', 'Role', 'Phone', 'Facility', 'Status'];
          const data = usersData.map(user => ({
            Name: user.name || 'N/A',
            Email: user.email || 'N/A',
            Role: user.role || 'N/A',
            Phone: user.phone || 'N/A',
            Facility: user.facilityName || 'N/A',
            Status: user.status || 'N/A'
          }));
          generateSimplePDF(doc, 'Users Report', data, columns);
        }
      } catch (autoTableError) {
        console.error('AutoTable failed, using simple PDF:', autoTableError);
        // Fallback to simple PDF
        const columns = ['Name', 'Email', 'Role', 'Phone', 'Facility', 'Status'];
        const data = usersData.map(user => ({
          Name: user.name || 'N/A',
          Email: user.email || 'N/A',
          Role: user.role || 'N/A',
          Phone: user.phone || 'N/A',
          Facility: user.facilityName || 'N/A',
          Status: user.status || 'N/A'
        }));
        generateSimplePDF(doc, 'Users Report', data, columns);
      }
    } catch (error) {
      console.error('Error generating users PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating users data', 14, startY);
    }
  };

  const generateFacilitiesPDF = (doc: jsPDF, startY: number) => {
    try {
      const facilitiesData = reportData.facilities || [];
      
      if (facilitiesData.length === 0) {
        doc.setFontSize(14);
        doc.text('No facilities data available', 14, startY);
        return;
      }

      // Try autoTable first, fallback to simple PDF
      try {
        const head = [['Name', 'Type', 'Location', 'Status', 'Contact']];
        const body = facilitiesData.map(facility => [
          facility.name || 'N/A',
          facility.type || 'N/A',
          facility.location || 'N/A',
          facility.status || 'N/A',
          facility.contact || 'N/A'
        ]);

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: head,
            body: body,
            startY: startY,
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [255, 204, 0], textColor: [0, 0, 0] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback to simple PDF
          const columns = ['Name', 'Type', 'Location', 'Status', 'Contact'];
          const data = facilitiesData.map(facility => ({
            Name: facility.name || 'N/A',
            Type: facility.type || 'N/A',
            Location: facility.location || 'N/A',
            Status: facility.status || 'N/A',
            Contact: facility.contact || 'N/A'
          }));
          generateSimplePDF(doc, 'Facilities Report', data, columns);
        }
      } catch (autoTableError) {
        console.error('AutoTable failed, using simple PDF:', autoTableError);
        // Fallback to simple PDF
        const columns = ['Name', 'Type', 'Location', 'Status', 'Contact'];
        const data = facilitiesData.map(facility => ({
          Name: facility.name || 'N/A',
          Type: facility.type || 'N/A',
          Location: facility.location || 'N/A',
          Status: facility.status || 'N/A',
          Contact: facility.contact || 'N/A'
        }));
        generateSimplePDF(doc, 'Facilities Report', data, columns);
      }
    } catch (error) {
      console.error('Error generating facilities PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating facilities data', 14, startY);
    }
  };

  const generateTransactionsPDF = (doc: jsPDF, startY: number) => {
    try {
      const transactionsData = reportData.transactions || [];
      
      if (transactionsData.length === 0) {
        doc.setFontSize(14);
        doc.text('No transactions data available', 14, startY);
        return;
      }

      // Try autoTable first, fallback to simple PDF
      try {
        const head = [['Item', 'Type', 'Quantity', 'Facility', 'Date']];
        const body = transactionsData.map(transaction => [
          transaction.itemName || 'N/A',
          transaction.type || 'N/A',
          transaction.quantity?.toString() || '0',
          transaction.facility || 'N/A',
          transaction.date ? new Date(transaction.date).toLocaleDateString() : 'N/A'
        ]);

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: head,
            body: body,
            startY: startY,
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [255, 204, 0], textColor: [0, 0, 0] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback to simple PDF
          const columns = ['Item', 'Type', 'Quantity', 'Facility', 'Date'];
          const data = transactionsData.map(transaction => ({
            Item: transaction.itemName || 'N/A',
            Type: transaction.type || 'N/A',
            Quantity: transaction.quantity?.toString() || '0',
            Facility: transaction.facility || 'N/A',
            Date: transaction.date ? new Date(transaction.date).toLocaleDateString() : 'N/A'
          }));
          generateSimplePDF(doc, 'Transactions Report', data, columns);
        }
      } catch (autoTableError) {
        console.error('AutoTable failed, using simple PDF:', autoTableError);
        // Fallback to simple PDF
        const columns = ['Item', 'Type', 'Quantity', 'Facility', 'Date'];
        const data = transactionsData.map(transaction => ({
          Item: transaction.itemName || 'N/A',
          Type: transaction.type || 'N/A',
          Quantity: transaction.quantity?.toString() || '0',
          Facility: transaction.facility || 'N/A',
          Date: transaction.date ? new Date(transaction.date).toLocaleDateString() : 'N/A'
        }));
        generateSimplePDF(doc, 'Transactions Report', data, columns);
      }
    } catch (error) {
      console.error('Error generating transactions PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating transactions data', 14, startY);
    }
  };

  const generateTransfersPDF = (doc: jsPDF, startY: number) => {
    try {
      const transfersData = reportData.transfers || [];
      
      if (transfersData.length === 0) {
        doc.setFontSize(14);
        doc.text('No transfers data available', 14, startY);
        return;
      }

      // Try autoTable first, fallback to simple PDF
      try {
        const head = [['Item', 'From', 'To', 'Quantity', 'Status', 'Date']];
        const body = transfersData.map(transfer => [
          transfer.itemName || 'N/A',
          transfer.fromFacility || 'N/A',
          transfer.toFacility || 'N/A',
          transfer.quantity?.toString() || '0',
          transfer.status || 'N/A',
          transfer.date ? new Date(transfer.date).toLocaleDateString() : 'N/A'
        ]);

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: head,
            body: body,
            startY: startY,
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [255, 204, 0], textColor: [0, 0, 0] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback to simple PDF
          const columns = ['Item', 'From', 'To', 'Quantity', 'Status', 'Date'];
          const data = transfersData.map(transfer => ({
            Item: transfer.itemName || 'N/A',
            From: transfer.fromFacility || 'N/A',
            To: transfer.toFacility || 'N/A',
            Quantity: transfer.quantity?.toString() || '0',
            Status: transfer.status || 'N/A',
            Date: transfer.date ? new Date(transfer.date).toLocaleDateString() : 'N/A'
          }));
          generateSimplePDF(doc, 'Transfers Report', data, columns);
        }
      } catch (autoTableError) {
        console.error('AutoTable failed, using simple PDF:', autoTableError);
        // Fallback to simple PDF
        const columns = ['Item', 'From', 'To', 'Quantity', 'Status', 'Date'];
        const data = transfersData.map(transfer => ({
          Item: transfer.itemName || 'N/A',
          From: transfer.fromFacility || 'N/A',
          To: transfer.toFacility || 'N/A',
          Quantity: transfer.quantity?.toString() || '0',
          Status: transfer.status || 'N/A',
          Date: transfer.date ? new Date(transfer.date).toLocaleDateString() : 'N/A'
        }));
        generateSimplePDF(doc, 'Transfers Report', data, columns);
      }
    } catch (error) {
      console.error('Error generating transfers PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating transfers data', 14, startY);
    }
  };

  const generateAllReportsPDF = (doc: jsPDF, startY: number) => {
    try {
      let currentY = startY;

      // Inventory Section
      doc.setFontSize(16);
      doc.text('Inventory Report', 14, currentY);
      currentY += 10;
      generateInventoryPDF(doc, currentY);
      currentY = (doc as any).lastAutoTable.finalY + 20;

      // Users Section
      doc.setFontSize(16);
      doc.text('Users Report', 14, currentY);
      currentY += 10;
      generateUsersPDF(doc, currentY);
      currentY = (doc as any).lastAutoTable.finalY + 20;

      // Facilities Section
      doc.setFontSize(16);
      doc.text('Facilities Report', 14, currentY);
      currentY += 10;
      generateFacilitiesPDF(doc, currentY);
      currentY = (doc as any).lastAutoTable.finalY + 20;

      // Transactions Section
      doc.setFontSize(16);
      doc.text('Transactions Report', 14, currentY);
      currentY += 10;
      generateTransactionsPDF(doc, currentY);
      currentY = (doc as any).lastAutoTable.finalY + 20;

      // Transfers Section
      doc.setFontSize(16);
      doc.text('Transfers Report', 14, currentY);
      currentY += 10;
      generateTransfersPDF(doc, currentY);
    } catch (error) {
      console.error('Error generating all reports PDF:', error);
      doc.setFontSize(14);
      doc.text('Error generating comprehensive report', 14, startY);
    }
  };

  // CSV Generation Functions
  const generateInventoryCSV = () => {
    const headers = ['Item Name', 'SKU', 'Category', 'Stock', 'Cost', 'Facility', 'Status', 'Description'];
    const rows = reportData.inventory.map(item => [
      item.name,
      item.sku,
      item.category,
      `${item.currentStock} ${item.unit}`,
      item.cost,
      item.facility,
      item.status,
      item.description
    ]);
    return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  };

  const generateUsersCSV = () => {
    const headers = ['Name', 'Email', 'Role', 'Facility', 'Status', 'Region', 'District', 'Phone'];
    const rows = reportData.users.map(user => [
      user.name,
      user.email,
      user.role,
      user.facilityName || '',
      user.status,
      user.region || '',
      user.district || '',
      user.phone || ''
    ]);
    return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  };

  const generateFacilitiesCSV = () => {
    const headers = ['Facility Name', 'Type', 'Location', 'Manager', 'Status', 'Capacity'];
    const rows = reportData.facilities.map(facility => [
      facility.name,
      facility.type,
      facility.location,
      facility.manager || '',
      facility.status,
      facility.capacity || ''
    ]);
    return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  };

  const generateTransactionsCSV = () => {
    const headers = ['Date', 'Type', 'Item', 'Quantity', 'Facility', 'Status', 'Notes'];
    const rows = reportData.transactions.map(transaction => [
      new Date(transaction.date).toLocaleDateString(),
      transaction.type,
      transaction.itemName,
      transaction.quantity,
      transaction.facility,
      transaction.status,
      transaction.notes || ''
    ]);
    return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  };

  const generateTransfersCSV = () => {
    const headers = ['Date', 'From', 'To', 'Item', 'Quantity', 'Status', 'Notes'];
    const rows = reportData.transfers.map(transfer => [
      new Date(transfer.date).toLocaleDateString(),
      transfer.fromFacility,
      transfer.toFacility,
      transfer.itemName,
      transfer.quantity,
      transfer.status,
      transfer.notes || ''
    ]);
    return [headers, ...rows].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  };

  const generateAllReportsCSV = () => {
    const sections = [
      { title: 'INVENTORY REPORT', data: generateInventoryCSV() },
      { title: 'USERS REPORT', data: generateUsersCSV() },
      { title: 'FACILITIES REPORT', data: generateFacilitiesCSV() },
      { title: 'TRANSACTIONS REPORT', data: generateTransactionsCSV() },
      { title: 'TRANSFERS REPORT', data: generateTransfersCSV() }
    ];

    return sections.map(section => 
      `\n${'='.repeat(50)}\n${section.title}\n${'='.repeat(50)}\n\n${section.data}`
    ).join('\n');
  };

  const getReportTitle = () => {
    const titles = {
      inventory: 'Inventory Report',
      users: 'Users Report',
      facilities: 'Facilities Report',
      transactions: 'Transactions Report',
      transfers: 'Transfers Report',
      all: 'Complete System Report'
    };
    return titles[reportConfig.type];
  };

  const handleGenerateReport = () => {
    console.log('Generating report:', reportConfig);
    if (reportConfig.format === 'pdf') {
      generatePDFReport();
    } else {
      generateCSVReport();
    }
  };

  const getReportStats = () => {
    const stats = {
      inventory: {
        total: reportData.inventory?.length || 0,
        lowStock: reportData.inventory?.filter(item => (item.currentStock || 0) <= (item.minStock || 0))?.length || 0,
        active: reportData.inventory?.filter(item => item.status === 'active')?.length || 0
      },
      users: {
        total: reportData.users?.length || 0,
        active: reportData.users?.filter(user => user.status === 'active')?.length || 0,
        byRole: reportData.users?.reduce((acc, user) => {
          acc[user.role] = (acc[user.role] || 0) + 1;
          return acc;
        }, {} as any) || {}
      },
      facilities: {
        total: reportData.facilities?.length || 0,
        active: reportData.facilities?.filter(facility => facility.status === 'active')?.length || 0
      },
      transactions: {
        total: reportData.transactions?.length || 0,
        thisMonth: reportData.transactions?.filter(t => 
          new Date(t.date).getMonth() === new Date().getMonth()
        )?.length || 0
      },
      transfers: {
        total: reportData.transfers?.length || 0,
        pending: reportData.transfers?.filter(t => t.status === 'pending')?.length || 0
      }
    };
    return stats;
  };

  const stats = getReportStats();

  console.log('Current report data:', reportData);
  console.log('Calculated stats:', stats);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Reports & Analytics</h1>
          <p className="text-gray-600 mt-2">Generate comprehensive reports for all system data</p>
        </div>
        <div className="flex items-center space-x-2">
          <RefreshCw className={`w-5 h-5 text-gray-500 ${loading ? 'animate-spin' : ''}`} />
          <span className="text-sm text-gray-500">Last updated: {new Date().toLocaleString()}</span>
        </div>
      </div>

      {/* Data Status */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <h3 className="text-sm font-medium text-red-800 mb-2">Error Loading Data</h3>
          <p className="text-xs text-red-700">{error}</p>
        </div>
      )}

      {/* Quick Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        <div className="bg-white rounded-lg shadow p-4">
          <div className="flex items-center">
            <Package className="w-8 h-8 text-blue-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Inventory Items</p>
              <p className="text-2xl font-bold text-gray-900">{stats.inventory.total}</p>
              <p className="text-xs text-red-600">{stats.inventory.lowStock} low stock</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-4">
          <div className="flex items-center">
            <Users className="w-8 h-8 text-green-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Users</p>
              <p className="text-2xl font-bold text-gray-900">{stats.users.total}</p>
              <p className="text-xs text-green-600">{stats.users.active} active</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-4">
          <div className="flex items-center">
            <Building className="w-8 h-8 text-purple-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Facilities</p>
              <p className="text-2xl font-bold text-gray-900">{stats.facilities.total}</p>
              <p className="text-xs text-green-600">{stats.facilities.active} active</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-4">
          <div className="flex items-center">
            <TrendingUp className="w-8 h-8 text-orange-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Transactions</p>
              <p className="text-2xl font-bold text-gray-900">{stats.transactions.total}</p>
              <p className="text-xs text-blue-600">{stats.transactions.thisMonth} this month</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-4">
          <div className="flex items-center">
            <Calendar className="w-8 h-8 text-indigo-600" />
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-600">Transfers</p>
              <p className="text-2xl font-bold text-gray-900">{stats.transfers.total}</p>
              <p className="text-xs text-yellow-600">{stats.transfers.pending} pending</p>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Generate Report Section */}
      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-medium text-gray-900">Quick Report Generation</h2>
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-red-600" />
            <FileSpreadsheet className="w-5 h-5 text-green-600" />
          </div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Report Type</label>
            <select
              value={reportConfig.type}
              onChange={(e) => setReportConfig(prev => ({ ...prev, type: e.target.value as any }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-uganda-yellow focus:border-transparent"
            >
              <option value="inventory">Inventory Report</option>
              <option value="users">Users Report</option>
              <option value="facilities">Facilities Report</option>
              <option value="transactions">Transactions Report</option>
              <option value="transfers">Transfers Report</option>
              <option value="all">Complete System Report</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Export Format</label>
            <div className="flex space-x-4">
              <label className="flex items-center">
                <input
                  type="radio"
                  value="pdf"
                  checked={reportConfig.format === 'pdf'}
                  onChange={(e) => setReportConfig(prev => ({ ...prev, format: e.target.value as 'pdf' | 'csv' }))}
                  className="w-4 h-4 text-uganda-yellow border-gray-300 focus:ring-uganda-yellow"
                />
                <span className="ml-2 text-sm">PDF</span>
              </label>
              <label className="flex items-center">
                <input
                  type="radio"
                  value="csv"
                  checked={reportConfig.format === 'csv'}
                  onChange={(e) => setReportConfig(prev => ({ ...prev, format: e.target.value as 'pdf' | 'csv' }))}
                  className="w-4 h-4 text-uganda-yellow border-gray-300 focus:ring-uganda-yellow"
                />
                <span className="ml-2 text-sm">CSV</span>
              </label>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Date Range</label>
            <select
              value={reportConfig.dateRange}
              onChange={(e) => setReportConfig(prev => ({ ...prev, dateRange: e.target.value as any }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-uganda-yellow focus:border-transparent"
            >
              <option value="all">All Time</option>
              <option value="today">Today</option>
              <option value="week">This Week</option>
              <option value="month">This Month</option>
              <option value="year">This Year</option>
            </select>
          </div>
        </div>

        {/* Generate Button */}
        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-600">
            <p>Report: <span className="font-medium">{getReportTitle()}</span></p>
            <p>Format: <span className="font-medium">{reportConfig.format.toUpperCase()}</span></p>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={testPDFGeneration}
              className="px-4 py-2 bg-gray-500 text-white font-medium rounded-lg hover:bg-gray-600 transition-colors"
            >
              Test PDF
            </button>
            <button
              onClick={handleGenerateReport}
              disabled={isGenerating}
              className="px-8 py-3 bg-uganda-yellow text-white font-medium rounded-lg hover:bg-yellow-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center text-lg"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-5 h-5 mr-2 animate-spin" />
                  Generating Report...
                </>
              ) : (
                <>
                  <Download className="w-5 h-5 mr-2" />
                  Generate Report
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Report Templates */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-lg font-medium text-gray-900">Quick Report Templates</h2>
          <p className="text-sm text-gray-600 mt-1">Pre-configured reports for common needs</p>
        </div>

        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              { title: 'Low Stock Alert', type: 'inventory', icon: AlertTriangle, color: 'text-red-600' },
              { title: 'User Activity', type: 'users', icon: Users, color: 'text-blue-600' },
              { title: 'Facility Overview', type: 'facilities', icon: Building, color: 'text-purple-600' },
              { title: 'Transaction Summary', type: 'transactions', icon: TrendingUp, color: 'text-orange-600' },
              { title: 'Transfer Status', type: 'transfers', icon: Calendar, color: 'text-indigo-600' },
              { title: 'Complete System', type: 'all', icon: BarChart3, color: 'text-green-600' }
            ].map((template) => (
              <button
                key={template.type}
                onClick={() => {
                  setReportConfig(prev => ({ ...prev, type: template.type as any }));
                  setSelectedReport(template.title);
                }}
                className={`p-4 border-2 rounded-lg transition-all hover:shadow-md ${
                  selectedReport === template.title 
                    ? 'border-uganda-yellow bg-yellow-50' 
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <div className="flex items-center space-x-3">
                  <template.icon className={`w-6 h-6 ${template.color}`} />
                  <div className="text-left">
                    <h3 className="font-medium text-gray-900">{template.title}</h3>
                    <p className="text-sm text-gray-600">Quick {template.type} report</p>
                  </div>
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Recent Reports */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-lg font-medium text-gray-900">Recent Reports</h2>
          <p className="text-sm text-gray-600 mt-1">Your recently generated reports</p>
        </div>

        <div className="p-6">
          <div className="text-center py-8 text-gray-500">
            <FileText className="w-12 h-12 mx-auto mb-3 text-gray-300" />
            <p className="text-sm">No recent reports</p>
            <p className="text-xs text-gray-400">Generate your first report to see it here</p>
          </div>
        </div>
      </div>
    </div>
  );
}